import type { Gender, Category } from "./types";

export const FPS = 10;
export const baseAPIUrl = "http://localhost:7878";
export const baseWSUrl = "ws://localhost:7878";
// export const baseAPIUrl = "192.168.1.114:7878";

export enum HttpClientBaseMehod {
    POST = 'POST',
    GET = 'GET',
    PUT = 'PUT'
}

export interface HttpClientBaseHeader {
    'Content-Type': string,
    'Authorization'?: string
}

export interface HttpClientBaseStatusCode {
    statusCode: number
    statusText: HttpStatusCode
}

export enum HttpStatusCode {
    Continue = 100,
    SwitchingProtocols = 101,
    Processing = 102,
    Ok = 200,
    Created = 201,
    Accepted = 202,
    NonAuthoritativeInformation = 203,
    NoContent = 204,
    ResetContent = 205,
    PartialContent = 206,
    MultiStatus = 207,
    AlreadyReported = 208,
    ImUsed = 226,
    MultipleChoices = 300,
    MovedPermanently = 301,
    Found = 302,
    SeeOther = 303,
    NotModified = 304,
    UseProxy = 305,
    SwitchProxy = 306,
    TemporaryRedirect = 307,
    PermanentRedirect = 308,
    BadRequest = 400,
    Unauthorized = 401,
    PaymentRequired = 402,
    Forbidden = 403,
    NotFound = 404,
    MethodNotAllowed = 405,
    NotAcceptable = 406,
    ProxyAuthenticationRequired = 407,
    RequestTimeout = 408,
    Conflict = 409,
    Gone = 410,
    LengthRequired = 411,
    PreconditionFailed = 412,
    PayloadTooLarge = 413,
    UriTooLong = 414,
    UnsupportedMediaType = 415,
    RangeNotSatisfiable = 416,
    ExpectationFailed = 417,
    IAmATeapot = 418,
    MisdirectedRequest = 421,
    UnprocessableEntity = 422,
    Locked = 423,
    FailedDependency = 424,
    UpgradeRequired = 426,
    PreconditionRequired = 428,
    TooManyRequests = 429,
    RequestHeaderFieldsTooLarge = 431,
    UnavailableForLegalReasons = 451,
    InternalServerError = 500,
    NotImplemented = 501,
    BadGateway = 502,
    ServiceUnavailable = 503,
    GatewayTimeout = 504,
    HttpVersionNotSupported = 505,
    VariantAlsoNegotiates = 506,
    InsufficientStorage = 507,
    LoopDetected = 508,
    NotExtended = 510,
    NetworkAuthenticationRequired = 511,
}

export const OutdoorEvents = [
    { Event: "100m" },
    { Event: "110mH" },
    { Event: "200m" },
    { Event: "300m" },
    { Event: "400m" },
    { Event: "400mH" },
    { Event: "500m" },
    { Event: "600m" },
    { Event: "800m" },
    { Event: "4x100m" },
    { Event: "4x200m" },
    { Event: "10,000m" },
    { Event: "1000m" },
    { Event: "100mH" },
    { Event: "10km" },
    { Event: "10kmW" },
    { Event: "1500m" },
    { Event: "2 Miles" },
    { Event: "2000m" },
    { Event: "2000mSC" },
    { Event: "3000m" },
    { Event: "3000mSC" },
    { Event: "3000mW" },
    { Event: "4x400m" },
    { Event: "5000m" },
    { Event: "5000mW" },
    { Event: "50kmW" },
    { Event: "5km" },
    { Event: "5kmW" },
    { Event: "DT" },
    { Event: "Heptathlon" },
    { Event: "Decathlon" },
    { Event: "HJ" },
    { Event: "HM" },
    { Event: "HT" },
    { Event: "JT" },
    { Event: "LJ" },
    { Event: "Marathon" },
    { Event: "Mile" },
    { Event: "PV" },
    { Event: "SP" },
    { Event: "TJ" },
]

export const IndoorEvents = [
    { Event: "50m" },
    { Event: "50mH" },
    { Event: "55m" },
    { Event: "55mH" },
    { Event: "60m" },
    { Event: "60mH" },
    { Event: "200m" },
    { Event: "300m" },
    { Event: "400m" },
    { Event: "400mH" },
    { Event: "500m" },
    { Event: "600m" },
    { Event: "800m" },
    { Event: "1000m" },
    { Event: "1500m" },
    { Event: "Mile" },
    { Event: "2000m" },
    { Event: "3000m" },
    { Event: "4x200m" },
    { Event: "4x400m" },
    { Event: "2" },
    { Event: "5000m" },
    { Event: "Pentathlon" },
    { Event: "Heptathlon" },
    { Event: "DT" },
    { Event: "HJ" },
    { Event: "HM" },
    { Event: "HT" },
    { Event: "JT" },
    { Event: "LJ" },
    { Event: "PV" },
    { Event: "SP" },
    { Event: "TJ" },
]